index_mapping = {
    "properties": {
        "code interne": {"type": "keyword"},
        "image produit": {"type": "keyword"},
        "code a barre": {"type": "keyword"},
        "REFERENCE": {"type": "keyword"},
        "SKU": {"type": "keyword"},
        "label produit": {"type": "text"},
        "SEO label produit": {"type": "text"},
        "categorie": {"type": "keyword"},
        "sous-categorie": {"type": "keyword"},
        "sous-sous-categorie": {"type": "keyword"},
        "categorie_id": {"type": "integer"},
        "collection": {"type": "text"},
        "Brève description": {"type": "text"},
        "Description": {"type": "text"},
        "Tags": {"type": "text"},
        "fiche technique": {"type": "text"},
        "alt image(71 caracteres)": {"type": "text"},
        "link": {"type": "keyword"},
        "meta-description": {"type": "text"},
        "meta title": {"type": "text"},
        "old_optimization grade": {"type": "keyword"},
        "new_optimization grade": {"type": "keyword"},
        "Poids": {"type": "float"},
        "Couleur": {"type": "keyword"},
        "color_id": {"type": "integer"},
        "Marque": {"type": "keyword"},
        "marque_id": {"type": "integer"},
        "garantie": {"type": "keyword"},
        "Stock": {"type": "float"},
        "fabriqué en": {"type": "keyword"},
        "est retournable": {"type": "keyword"},
        "Prix vendeur": {"type": "float"},
        "Prix brute": {"type": "float"},
        "Prix Promo": {"type": "float"},
        "lien (web et video )\n": {"type": "keyword"},
        "lien": {"type": "keyword"},
        "image principale": {"type": "keyword"},
        "images secondaires": {"type": "keyword"},
        "seller-id": {"type": "keyword"},
        "Created by": {"type": "text"},
        "ProduitVecteur": {
            "type": "dense_vector",
            "dims": 768,
            "index": True,
            "similarity": "cosine",
        },
        "VecteurDescription": {
            "type": "dense_vector",
            "dims": 768,
            "index": True,
            "similarity": "cosine",
        },
    }
}